version: '3.8'

services:
  # BANCO DE DADOS
  db-comunidade:
    image: postgres:latest
    container_name: db-comunidade
    environment:
      POSTGRES_DB: api-comunidade
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - shared_network

  # APLICAÇÃO
  api-comunidade:
    build: .
    container_name: api-comunidade
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-comunidade:5432/api-comunidade
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      JAVA_TOOL_OPTIONS=-Duser.timezone: America/Sao_Paulo
    depends_on:
      - db-comunidade
    restart: always
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  postgres_data:
